application: weplux
version: 1
runtime: go
api_version: go1

handlers:
- url: /(.*\.(htm|html|js|css|txt|png|webp|jpeg|jpg|gif|ico|obj|ply))
  static_files: static/\1
  upload: static/.*

handlers:
- url: /(.*)/
  static_files: static/\1/index.html
  upload: static/\1/index.html

- url: .*
  script: _go_app
